### ISSUE TITLE
apollo 提示系统错误请联系管理员

### ISSUE THREAD

**Issue by YixiaoOneSmile** [zengqinglei/FabricDemo#1]
作者您好，我是.net core 微服务的初学者，看到您的文章觉得受益很大，在部署.net core 微服务时遇到了一些问题，比如Apollo一直报错等，能否进行交流和解答

**Comment by zengqinglei** [comment]
HI:

[请参考回复](https://github.com/zengqinglei/microservice-deploy/issues/1)
